name: justfocus
version: '3.0.0'
summary: A distraction-free focus timer.
description: |
  A distraction-free focus timer
grade: edge
confinement: strict
base: core24
icon: snap/gui/icon.png
title: JustFocus
website: https://andre-i.eu
issues: https://github.com/goto-eof
compression: xz
apps:
  justfocus:
    command: executor
    extensions: [ gnome ]
    plugs:
      - desktop
      - wayland
      - opengl
platforms:
  amd64:
    build-on: [ amd64 ]
    build-for: [ amd64 ]
  arm64:
    build-on: [ arm64 ]
    build-for: [ arm64 ]
parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local
  application:
    plugin: maven
    source: .
    build-packages:
      - openjdk-21-jdk
      - maven
    override-build: |
      getproxy () {
        host=$(echo "$1" | sed -E 's|https?://([^:/]*):?[0-9]*/?|\1|')
        port=$(echo "$1" | sed -E 's|https?://[^:/]*:?([0-9]*)/?|\1|')
      }
      
      http=""
      https=""
      
      if [ -n "${http_proxy:-}" ]; then
          getproxy "$http_proxy"
          http="-Dhttp.proxyHost=$host -Dhttp.proxyPort=$port"
      fi
      
      if [ -n "${https_proxy:-}" ]; then
          getproxy "$https_proxy"
          https="-Dhttps.proxyHost=$host -Dhttps.proxyPort=$port"
      fi
      
      export MAVEN_OPTS="$http $https"
      
      mvn clean install -DskipTests
      
      
       if [ "$SNAP_ARCH" = "amd64" ]; then
          JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"
      elif [ "$SNAP_ARCH" = "arm64" ]; then
          JAVA_HOME="/usr/lib/jvm/java-21-openjdk-arm64"
      fi
      
      "$JAVA_HOME"/bin/jlink --module-path "$JAVA_HOME"/jmods \
                             --add-modules java.base,java.desktop \
                             --output custom-jre \
                             --compress=2 \
                             --no-header-files \
                             --no-man-pages
      
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/jar
      
      cp target/just-focus.jar "$SNAPCRAFT_PART_INSTALL"/jar/just-focus.jar
      cp -r custom-jre "$SNAPCRAFT_PART_INSTALL"/
    stage-packages:
      - libglu1-mesa
      - libxrender1