name: justfocus
version: '1.0.0'
summary: A distraction-free focus timer.
description: |
  A distraction-free focus timer
grade: stable
confinement: strict
base: core24
icon: snap/gui/icon.png
title: JustFocus
website: https://andre-i.eu
issues: https://github.com/goto-eof
license: MIT
compression: xz
apps:
  justfocus:
    command: executor
    extensions: [ gnome ]
    plugs:
      - desktop
      - wayland
platforms:
  amd64:
    build-on: [ amd64 ]
    build-for: [ amd64 ]
  arm64:
    build-on: [ arm64 ]
    build-for: [ arm64 ]
parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local
  application:
    plugin: maven
    source: .
    build-packages:
      - openjdk-21-jdk
      - maven
    override-build: |
      getproxy() {
          local proxy_url="$1"
          local proto=$(echo "$proxy_url" | sed -E 's/^(http|https):\/\///; s/:.*//')
          local user_pass=$(echo "$proxy_url" | sed -E 's/^(http|https):\/\///; s/@.*//; s/:/ /' | grep " ")
          local host_port=$(echo "$proxy_url" | sed -E 's/^(http|https):\/\///; s/.*@//' | grep ":")
      
          if [ -n "$user_pass" ]; then
              user=$(echo "$user_pass" | cut -d' ' -f1)
              pass=$(echo "$user_pass" | cut -d' ' -f2)
          fi
      
          if [ -n "$host_port" ]; then
              host=$(echo "$host_port" | cut -d':' -f1)
              port=$(echo "$host_port" | cut -d':' -f2)
          else
              host=$(echo "$proxy_url" | sed -E 's/^(http|https):\/\///')
              port="" # Default port for http/https will be used if not specified
          fi
      }
      
      http=""
      https=""
      
      if [ -n "${http_proxy:-}" ]; then
          getproxy "$http_proxy"
          http="-Dhttp.proxyHost=$host -Dhttp.proxyPort=$port"
      fi
      
      if [ -n "${https_proxy:-}" ]; then
          getproxy "$https_proxy"
          https="-Dhttps.proxyHost=$host -Dhttps.proxyPort=$port"
      fi
      
      export MAVEN_OPTS="$http $https"
      # --- FINE GESTIONE PROXY PER MAVEN ---
      
      # 1. Build your application using Maven
      # This command will now respect the MAVEN_OPTS set above
      mvn clean install -DskipTests
      
      # Assuming your main JAR is in 'target/your-app.jar' after Maven build
      # And any other required libraries are in 'target/lib/'
      
      # 2. Identify modules using jdeps (adjust module path for your actual libs)
      # You might need to adjust 'your-app.jar' path if Maven outputs it elsewhere
      # For a Swing app, java.base and java.desktop are minimums.
      # Example: jdeps --print-module-deps target/your-app.jar
      
      # 3. Create the custom JRE using jlink
      # Use the JDK installed via build-packages. Adjust JAVA_HOME path if different.
      # Typically, it's /usr/lib/jvm/java-<version>-openjdk-<arch>
      JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" # VERIFICA QUESTO PERCORSO!
      "$JAVA_HOME"/bin/jlink --module-path "$JAVA_HOME"/jmods \
                             --add-modules java.base,java.desktop \
                             --output custom-jre \
                             --compress=2 \
                             --no-header-files \
                             --no-man-pages
      
      # 4. Copy your application JAR and the custom JRE to the install directory
      # Assuming Maven puts your main JAR in 'target/'
      cp target/your-app.jar "$SNAPCRAFT_PART_INSTALL"/
      cp -r custom-jre "$SNAPCRAFT_PART_INSTALL"/
    stage-packages:
      - openjdk-21-jre
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-21-openjdk-*64/lib/security/blacklisted.certs

